
/*
CREATE TABLE IF NOT EXISTS dimAltTitles (
    Alt_Title_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Alt_Title VARCHAR(150),
    Short_Title VARCHAR(100),
    Source VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ONET_SOC_Code) REFERENCES factJobSkills(ONET_SOC_Code)
);


CREATE TABLE IF NOT EXISTS dimTasks (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Task_ID INTEGER(8),
    Task VARCHAR(1000),
    Task_Type VARCHAR(12),
    Incumbents_Responding INTEGER(4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ONET_SOC_Code) REFERENCES factJobSkills(ONET_SOC_Code)
);

*/

CREATE TABLE IF NOT EXISTS dimTechSkills (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Example VARCHAR(150),
    Commodity_Code INTEGER(8),
    Commodity_Title VARCHAR(150),
    Hot_Tech BOOLEAN,
    In_Demand BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ONET_SOC_Code) REFERENCES factJobSkills(ONET_SOC_Code)
);

/*
CREATE TABLE IF NOT EXISTS dimTools (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Example VARCHAR(150),
    Commodity_Code INTEGER(8),
    Commodity_Title VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ONET_SOC_Code) REFERENCES factJobSkills(ONET_SOC_Code)
);

*/

CREATE TABLE IF NOT EXISTS dimSkills (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Skill_element_ID VARCHAR(20),
    Skill VARCHAR(150),
    Scale_ID VARCHAR(3),
    Scale_Value FLOAT(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ONET_SOC_Code) REFERENCES factJobSkills(ONET_SOC_Code)
);



CREATE TABLE IF NOT EXISTS dimJobInfo (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Job_Title VARCHAR(150),
    Job_Description VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    
);


CREATE TABLE IF NOT EXISTS factJobSkills (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ONET_SOC_Code VARCHAR(10),
    Skill_ID INTEGER(8), 
    FOREIGN KEY(Skill_ID) REFERENCES dimSkills(ID),
    Tech_Skill_ID INTEGER(8),
    FOREIGN KEY(Tech_Skill_ID) REFERENCES dimTechSkills(ID),
    Job_ID INTEGER(8),
    FOREIGN KEY(Job_ID) REFERENCES dimJobInfo(ID),
    Job_Title VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

